services:
  demo: null # Disabilita il servizio demo, se possibile, per evitare confusione
  tms:
    use_grid_names: true
  wms:
    image_formats: ['image/png']
    md:
      title: "Catasto Agenzia Entrate via MapProxy"
      abstract: "Proxy + cache del WMS cartografia.agenziaentrate.gov.it"
      online_resource: "https://mapproxy-italia.onrender.com/service"
      contact:
        person: "Antonio Rocca"
        city: "Italia"
        country: "IT"

layers:
  - name: catasto_cache
    title: Catasto (Agenzia Entrate) - cache 12h
    sources: [catasto_cache]

sources:
  catasto_wms:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php
      # Lista completa dei layer, inclusi i livelli di vestizione (codice_plla e Simbolo_graffa) 
      layers: CP.CadastralZoning,strade,acque,CP.CadastralParcel,fabbricati,codice_plla,Simbolo_graffa 
      transparent: true
      format: image/png
    wms_opts:
      [cite_start]version: 1.1.1 # Versione corretta che ha funzionato nel test 
    [cite_start]supported_srs: ['EPSG:6706', 'EPSG:3857'] # Supporta il nativo Catasto (6706) e la griglia Web Mercator (3857) 
    http:
      client_timeout: 180
      headers:
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'

caches:
  catasto_cache:
    grids: [webmercator]
    sources: [catasto_wms]
    format: image/png
    cache:
      type: file
      directory: /mapproxy/cache_data/tiles/catasto
      directory_layout: tms
    meta_size: [2, 2]
    meta_buffer: 64
    refresh_before:
      hours: 12

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
    origin: nw

globals:
  cache:
    base_dir: /mapproxy/cache_data
    lock_dir: /mapproxy/cache_data/tile_locks

  tiles:
    expires_hours: 12

  image:
    resampling_method: bilinear
    jpeg_quality: 90
