services:
  demo:
  tms:
    use_grid_names: true
  wmts:
  wms:
    srs: ['EPSG:3857', 'EPSG:4326', 'EPSG:32632', 'EPSG:32633', 'EPSG:6706', 'EPSG:25832', 'EPSG:25833', 'EPSG:3003', 'EPSG:3004']
    image_formats: ['image/png', 'image/jpeg']
    md:
      title: MapProxy Italia - Catasto WMS
      abstract: Servizio WMS della cartografia catastale con supporto multi-CRS
      online_resource: https://mapproxy-italia.onrender.com

layers:
  - name: catastoALL
    title: Catasto Completo
    sources: [catasto_cache]
  - name: catasto
    title: Catasto Italia
    sources: [catasto_cache]

sources:
  catasto_wms:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php
      layers: CP.CadastralParcel,CP.CadastralZoning,fabbricati,acque,strade,codice_plla,simbolo_graffa
      transparent: true
    wms_opts:
      version: 1.1.1
    supported_srs: ['EPSG:6706']
    http:
      client_timeout: 300
      headers:
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'

grids:
  italygrid:
    srs: EPSG:6706
    bbox: [6.5, 35.0, 19.0, 48.0]
    origin: nw

  webmercator:
    srs: EPSG:3857
    origin: nw

caches:
  catasto_native:
    grids: [italygrid]
    sources: [catasto_wms]
    cache:
      type: file
      directory: /mapproxy/cache_data/tiles/native
      directory_layout: tms
    format: image/png
    meta_size: [4, 4]
    meta_buffer: 20

  catasto_cache:
    grids: [webmercator]
    sources: [catasto_native]
    cache:
      type: file
      directory: /mapproxy/cache_data/tiles/mercator
      directory_layout: tms
    format: image/png
    meta_size: [2, 2]
    meta_buffer: 20

globals:
  cache:
    base_dir: /mapproxy/cache_data
    lock_dir: /mapproxy/cache_data/tile_locks
  image:
    resampling_method: bilinear
