services:
  demo: {}
  tms:
    use_grid_names: true
  tile:
    use_grid_names: true
  wms:
    image_formats: ['image/png']
    md:
      title: "Catasto Agenzia Entrate via MapProxy"
      abstract: "Proxy + cache del WMS cartografia.agenziaentrate.gov.it"
      online_resource: "https://mapproxy-italia.onrender.com/service"
      contact:
        person: "Antonio Rocca"
        city: "Italia"
        country: "IT"

layers:
  - name: catasto_cache
    title: Catasto (Agenzia Entrate) - cache 12h
    sources: [catasto_cache]

sources:
  catasto_wms:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php
      layers: CP.CadastralZoning,strade,acque,CP.CadastralParcel,fabbricati
      transparent: true
      format: image/png
    # Il WMS del catasto lavora in EPSG:6706, NON in 3857
    wms_opts:
      version: 1.3.0
    supported_srs: ['EPSG:6706']
    http:
      client_timeout: 180
      headers:
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'

caches:
  catasto_cache:
    grids: [webmercator]
    sources: [catasto_wms]
    format: image/png
    cache:
      type: file
      # directory principale di cache (volume montato su Render)
      directory: /mapproxy/cache_data/tiles/catasto
      directory_layout: tms
    meta_size: [2, 2]
    meta_buffer: 64
    # la cache viene considerata “vecchia” dopo 12 ore
    refresh_before:
      hours: 12

grids:
  # Grid esterna in EPSG:3857, compatibile OSM/Leaflet
  webmercator:
    base: GLOBAL_WEBMERCATOR
    origin: nw

globals:
  cache:
    # Base dir per tutte le cache (lock, ecc.)
    base_dir: /mapproxy/cache_data
    lock_dir: /mapproxy/cache_data/tile_locks

  # Imposta header HTTP di cache lato client (browser) a 12 ore
  tiles:
    expires_hours: 12

  image:
    resampling_method: bilinear
    jpeg_quality: 90

  # per debug, lascia pure così o aumenta se vuoi più log
  # (dipende dal tuo entrypoint/uwsgi)
  # logger:
  #   root:
  #     level: INFO
