services:
  demo: null
  tms:
    use_grid_names: true
    origin: nw
  wms:
    image_formats: ['image/png', 'image/jpeg']
    srs: ['EPSG:3857', 'EPSG:4326']
    md:
      title: "Catasto Agenzia Entrate - Particelle + Numeri + Fabbricati"
      abstract: "Proxy con cache per catasto italiano (funziona su Render)"

layers:
  - name: catasto_completo
    title: Catasto completo (contorni + fabbricati + numeri particella - cache 12h)
    sources: [catasto_cache]

sources:
  wms_agenzia:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php
      version: 1.3.0
      layers: CP.CadastralParcel,fabbricati,CP.CadastralParcelNumber
      transparent: true
    supported_srs: ['EPSG:3857', 'EPSG:4326', 'EPSG:6706']
    coverage:
      bbox: [9.0, 36.5, 18.0, 47.0]  # Solo centro-sud Italia per test rapidi (evita blocchi su bbox grandi)
      srs: 'EPSG:4326'
    http:
      client_timeout: 60  # Ridotto per evitare timeout su Render
      headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
        Referer: https://www.google.it/maps
        Accept: image/png,image/*;q=0.8
        Connection: keep-alive

caches:
  catasto_cache:
    sources: [wms_agenzia]
    grids: [webmercator]
    format: image/png
    cache:
      type: file
      directory: /mapproxy/cache_data/tiles/catasto_completo
      directory_layout: tms
    meta_size: [4, 4]  # Piccolo per test rapidi
    meta_buffer: 50
    refresh_before:
      hours: 12

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR

globals:
  cache:
    base_dir: /mapproxy/cache_data
    lock_dir: /mapproxy/cache_data/locks

  http:
    client_timeout: 60
    pool_size: 10  # Più connessioni per velocizzare

  image:
    resampling_method: bilinear
    antialias: true
    paletted: false
    transparent_color: null
