services:
  demo:
  tms:
    use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy Italia - Catasto

layers:
  - name: catasto
    title: Catasto Italia
    sources: [catasto_cache]

sources:
  catasto_wms:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php
      layers: CP.CadastralZoning,strade,acque,CP.CadastralParcel,fabbricati
      transparent: true
      format: image/png
    wms_opts:
      version: 1.3.0
    supported_srs: ['EPSG:6706', 'EPSG:3857']
    http:
      client_timeout: 180
      headers:
        User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'

grids:
  webmercator:
    srs: EPSG:3857
    origin: nw

caches:
  catasto_cache:
    grids: [webmercator]
    sources: [catasto_wms]
    cache:
      type: file
      directory: /mapproxy/cache_data/tiles/catasto   # <— sul Disk
      directory_layout: tms
      # TTL cache MapProxy: rigenera se più vecchio di 12 ore
      refresh_before:
        hours: 12
    format: image/png
    meta_size: [2, 2]
    meta_buffer: 50
    upscale_tiles: 1
    concurrent_tile_creators: 2

globals:
  cache:
    base_dir: /mapproxy/cache_data                    # <— Disk
    lock_dir: /mapproxy/cache_data/tile_locks
  tiles:
    expires_hours: 12                                 # TTL browser
  image:
    resampling_method: bilinear
    paletted: false
