services:
  demo: null
  tms:
    use_grid_names: true
    origin: nw
  wms:
    srs: ['EPSG:6706', 'EPSG:3857', 'EPSG:4326']
    image_formats: ['image/png']
    md:
      title: "Catasto Agenzia Entrate - Particelle + Numeri + Fabbricati"
      abstract: "Proxy con cache per catasto italiano"
    # Aggiungi endpoint health per Render
    health:
      disable: false

layers:
  - name: catasto_completo
    title: Catasto completo (contorni + fabbricati + numeri)
    sources: [catasto_cache]

sources:
  wms_agenzia:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php?
      version: 1.1.1
      layers: CP.CadastralParcel,CP.CadastralZoning,fabbricati,CP.CadastralParcelNumber
      transparent: true
      format: image/png
      srs: EPSG:6706
      styles: ''
    supported_srs: ['EPSG:6706']  # IMPORTANTE: usa solo questo SRS
    wms_opts:
      version: 1.1.1
    coverage:
      bbox: [10.0, 36.0, 19.0, 48.0]  # Italia
      srs: 'EPSG:4326'
    http:
      client_timeout: 60
      retries: 3
      headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
        Referer: https://www.google.it/
        Accept: image/png
        Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7

caches:
  catasto_cache:
    sources: [wms_agenzia]
    grids: [epsg6706_grid]
    cache:
      type: file
      directory: /tmp/mapproxy_cache  # Render usa filesystem temporaneo
      directory_layout: tms
    meta_size: [2, 2]
    meta_buffer: 10
    format: image/png
    # Su Render, la cache è temporanea, quindi refresh breve
    refresh_before:
      minutes: 30

grids:
  # Griglia specifica per EPSG:6706 (RDN2008 / UTM zone 32N)
  epsg6706_grid:
    srs: 'EPSG:6706'
    bbox: [10.0, 36.0, 19.0, 48.0]
    bbox_srs: 'EPSG:4326'
    res: [
      4000.0, 2000.0, 1000.0, 500.0, 250.0, 125.0, 
      62.5, 31.25, 15.625, 7.8125, 3.90625, 1.953125
    ]
    origin: nw
    tile_size: [256, 256]

globals:
  cache:
    base_dir: /tmp/mapproxy_cache
    lock_dir: /tmp/mapproxy_cache/locks
  image:
    resampling_method: bilinear
    mode: rgba
  http:
    client_timeout: 60
    pool_size: 10
