services:
  demo:
  tms:
    use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy Italia

layers:
  - name: catasto
    title: Catasto Italia
    sources: [catasto_cache]

sources:
  catasto_wms:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php
      layers: CP.CadastralZoning,strade,acque,CP.CadastralParcel,fabbricati,vestizioni
      transparent: true
    supported_srs: ['EPSG:6706', 'EPSG:3857', 'EPSG:4326']

grids:
  webmercator:
    srs: EPSG:3857
    origin: nw
  
  utm32n:
    srs: EPSG:6706
    origin: nw

caches:
  catasto_cache:
    grids: [webmercator, utm32n]
    sources: [catasto_wms]
    cache:
      type: file
      directory: /mapproxy/cache_data/tiles
      directory_layout: tms
    format: image/png
    meta_size: [4, 4]
    meta_buffer: 20
    request_format: image/png

globals:
  cache:
    base_dir: /mapproxy/cache_data
    lock_dir: /mapproxy/cache_data/tile_locks
  image:
    resampling_method: bilinear
    paletted: false
