services:
  demo: null
  tms:
    use_grid_names: true
    origin: nw
  wms:
    image_formats: ['image/png']
    srs: ['EPSG:3857', 'EPSG:4326', 'EPSG:6706']
    md:
      title: "Catasto Agenzia Entrate via MapProxy"
      abstract: "Proxy + cache funzionante del WMS Agenzia Entrate"
      online_resource: "https://mapproxy-italia.onrender.com/service"

layers:
  - name: catasto
    title: Catasto Particelle + Fabbricati (cache 12h)
    sources: [catasto_cache]

sources:
  catasto_wms:
    type: wms
    req:
      url: https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php
      layers: CP.CadastralParcel,fabbricati
      transparent: true
      version: 1.3.0           # importante: 1.3.0 funziona meglio di 1.1.1
    supported_srs: ['EPSG:6706', 'EPSG:3857', 'EPSG:4326']
    coverage:
      bbox: [6.5, 35.0, 18.7, 47.1]
      srs: 'EPSG:4326'
    wms_opts:
      map: true                # forza l'uso di GetMap anche per tile
    http:
      client_timeout: 120
      headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
        Referer: https://mapproxy-italia.onrender.com/

caches:
  catasto_cache:
    grids: [webmercator]
    sources: [catasto_wms]
    format: image/png
    cache:
      type: file
      directory: /mapproxy/cache_data/tiles/catasto
      directory_layout: tms
    meta_size: [8, 8]          # più grande = meno lock contention
    meta_buffer: 100
    bulk_meta_tiles: true
    refresh_before:
      hours: 12

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR

globals:
  cache:
    base_dir: /mapproxy/cache_data
    lock_dir: /mapproxy/cache_data/locks
    lock_timeout: 300

  http:
    client_timeout: 120

  image:
    resampling_method: bilinear
    antialias: true
    paletted: false
